// src/fixes.ts
// Turn findings into a PR-ready fix pack (#35). For the deterministic classes (missing/weak security
// headers, cookie flags, security.txt, directory listing) we emit copy-paste config for the common
// platforms; for everything else we carry the finding's own one-line fix. The hosted pipeline (#35) turns
// this pack into an actual branch + PR against a connected repo; here we produce the human-appliable pack.

import type { Finding } from './types.js';
import { vtaCode } from './catalog.js';

/** The concrete response-header line a missing/weak `header.<name>` finding should add. */
const HEADER_FIX: Record<string, string> = {
  'header.strict-transport-security': 'Strict-Transport-Security: max-age=31536000; includeSubDomains; preload',
  'header.x-content-type-options': 'X-Content-Type-Options: nosniff',
  'header.x-frame-options': 'X-Frame-Options: DENY',
  'header.referrer-policy': 'Referrer-Policy: strict-origin-when-cross-origin',
  'header.content-security-policy': "Content-Security-Policy: default-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'",
  'header.permissions-policy': 'Permissions-Policy: camera=(), microphone=(), geolocation=()',
  'header.cross-origin-opener-policy': 'Cross-Origin-Opener-Policy: same-origin',
  'header.cross-origin-resource-policy': 'Cross-Origin-Resource-Policy: same-origin',
};

/** The security headers a scan says are missing/weak, as concrete `Name: value` lines (deduped, ordered). */
export function missingHeaderLines(findings: Finding[]): string[] {
  const lines: string[] = [];
  for (const id of Object.keys(HEADER_FIX)) {
    if (findings.some((f) => !f.pass && f.id === id)) lines.push(HEADER_FIX[id]);
  }
  return lines;
}

/** Render the missing headers as ready-to-paste config for the common hosting platforms. */
function headerSnippets(lines: string[]): string {
  if (!lines.length) return '';
  const pairs = lines.map((l) => { const i = l.indexOf(':'); return [l.slice(0, i).trim(), l.slice(i + 1).trim()]; });
  const nextjs = [
    '```js',
    '// next.config.js — add to headers()',
    'async headers() {',
    '  return [{ source: "/(.*)", headers: [',
    ...pairs.map(([k, v]) => `    { key: ${JSON.stringify(k)}, value: ${JSON.stringify(v)} },`),
    '  ] }];',
    '}',
    '```',
  ].join('\n');
  const netlify = ['```', '# netlify.toml / _headers  (for /*)', ...lines.map((l) => `  ${l}`), '```'].join('\n');
  const nginx = ['```nginx', ...pairs.map(([k, v]) => `add_header ${k} "${v}" always;`), '```'].join('\n');
  const vercel = [
    '```json',
    '// vercel.json',
    '{ "headers": [ { "source": "/(.*)", "headers": [',
    ...pairs.map(([k, v]) => `  { "key": ${JSON.stringify(k)}, "value": ${JSON.stringify(v)} },`),
    '] } ] }',
    '```',
  ].join('\n');
  return ['### Add these security headers\n', '**Next.js**', nextjs, '', '**Netlify (`_headers`)**', netlify, '', '**nginx**', nginx, '', '**Vercel**', vercel].join('\n');
}

const SEV_ORDER = ['high', 'medium', 'low', 'info'] as const;

/**
 * Render a fix pack: a consolidated security-headers block (when relevant) plus a per-finding checklist
 * (VTA number, severity, what/why, and the one-line fix), grouped by severity. PR-ready markdown.
 */
export function renderFixPack(findings: Finding[], opts: { target: string; projectName?: string }): string {
  const fails = findings.filter((f) => !f.pass && f.severity !== 'info');
  const L: string[] = [];
  L.push(`# Fix pack — ${opts.projectName || opts.target}`);
  L.push('');
  L.push(`Generated by VibeTesting Agent for **${opts.target}**. ${fails.length} issue(s) to fix, keyed by test number.`);
  L.push('');

  const headerLines = missingHeaderLines(findings);
  if (headerLines.length) { L.push(headerSnippets(headerLines)); L.push(''); }

  for (const sev of SEV_ORDER) {
    const group = fails.filter((f) => f.severity === sev);
    if (!group.length) continue;
    L.push(`## ${sev.toUpperCase()} (${group.length})`);
    L.push('');
    for (const f of group) {
      L.push(`- [ ] **${vtaCode(f.id)}** — ${f.title}`);
      L.push(`  - ${f.detail}`);
      if (f.fix) L.push(`  - **Fix:** ${f.fix}`);
      const hl = HEADER_FIX[f.id];
      if (hl) L.push(`  - **Header:** \`${hl}\``);
    }
    L.push('');
  }
  if (!fails.length) L.push('_No issues to fix — clean scan._');
  return L.join('\n') + '\n';
}
