// Generate Gherkin (.feature) scenarios from vibetesting-agent findings so each new repo gets
// executable security acceptance criteria. Default style is BDD that maps 1:1 to finding ids.

import type { Finding, Severity } from './types.js';

const SEV_RANK: Record<Severity, number> = { high: 0, medium: 1, low: 2, info: 3 };

export interface GherkinOptions {
  url: string;
  projectName?: string;
  /** Only failing findings (default true). */
  failuresOnly?: boolean;
  /** Tag scenarios with @security @high etc. */
  tags?: boolean;
}

function slug(id: string): string {
  return id.replace(/[^a-zA-Z0-9]+/g, '-').replace(/^-|-$/g, '').toLowerCase();
}

function featureName(f: Finding): string {
  return f.title.replace(/"/g, "'");
}

/**
 * Single multi-scenario feature file covering all (failing) findings.
 */
export function renderGherkinFeature(findings: Finding[], opts: GherkinOptions): string {
  const onlyFail = opts.failuresOnly !== false;
  const list = (onlyFail ? findings.filter((f) => !f.pass) : findings)
    .slice()
    .sort((a, b) => SEV_RANK[a.severity] - SEV_RANK[b.severity]);

  const name = opts.projectName || 'Application';
  const lines: string[] = [
    `# Generated by vibetesting-agent — do not hand-edit ids; regenerate after scans.`,
    `# Target: ${opts.url}`,
    `# Scenarios: ${list.length}`,
    ``,
    `Feature: ${name} security hygiene`,
    `  As a vibe coder shipping with AI`,
    `  I want continuous security acceptance tests`,
    `  So regressions are caught on every software update`,
    ``,
    `  Background:`,
    `    Given the deployed application at "${opts.url}"`,
    `    And vibetesting-agent is available via npx`,
    ``,
  ];

  if (!list.length) {
    lines.push(`  @security @green`);
    lines.push(`  Scenario: Clean ship score`);
    lines.push(`    When I run a full black-box scan`);
    lines.push(`    Then there should be no high severity failures`);
    lines.push(`    And the security grade should be at least "B"`);
    lines.push(``);
    return lines.join('\n');
  }

  for (const f of list) {
    const tags = opts.tags === false
      ? ''
      : `  @security @sev-${f.severity} @cat-${f.category} @id-${slug(f.id)}`;
    if (tags) lines.push(tags);
    lines.push(`  Scenario: ${featureName(f)}`);
    lines.push(`    # finding: ${f.id}`);
    lines.push(`    # severity: ${f.severity}`);
    lines.push(`    Given finding "${f.id}" is monitored`);
    lines.push(`    When I scan category "${f.category}"`);
    if (f.pass) {
      lines.push(`    Then finding "${f.id}" should pass`);
    } else {
      lines.push(`    Then finding "${f.id}" should eventually pass`);
      lines.push(`    # current: FAIL — ${f.detail.replace(/\n/g, ' ')}`);
      if (f.fix) lines.push(`    # fix: ${f.fix.replace(/\n/g, ' ')}`);
    }
    lines.push(``);
  }

  // Regression suite: always fail CI on new highs
  lines.push(`  @security @gate`);
  lines.push(`  Scenario: No new high-severity regressions`);
  lines.push(`    When I run a full black-box scan with baseline`);
  lines.push(`    Then there should be no new high severity failures`);
  lines.push(``);

  return lines.join('\n');
}

/**
 * One file per finding under features/security/ — good for PRs that fix one issue.
 */
export function renderGherkinFiles(
  findings: Finding[],
  opts: GherkinOptions,
): { path: string; content: string }[] {
  const onlyFail = opts.failuresOnly !== false;
  const list = onlyFail ? findings.filter((f) => !f.pass) : findings;
  return list.map((f) => ({
    path: `features/security/${slug(f.id)}.feature`,
    content: renderGherkinFeature([f], { ...opts, failuresOnly: false }),
  }));
}

/**
 * Minimal step-definition stub (JavaScript) that shells to vibetesting-agent --json.
 * Drop into features/support/vibetesting-agent.steps.mjs for cucumber-js.
 */
export function renderGherkinStepStub(): string {
  return `// features/support/vibetesting-agent.steps.mjs
// Minimal cucumber-js steps that re-run vibetesting-agent. Install: npm i -D @cucumber/cucumber
import { Given, When, Then, setDefaultTimeout } from '@cucumber/cucumber';
import { spawnSync } from 'node:child_process';
import assert from 'node:assert/strict';

setDefaultTimeout(120_000);

let targetUrl = process.env.ANAL_PROBE_URL || '';
let lastFindings = [];
let lastSummary = null;

function runProbe(args = []) {
  if (!targetUrl) throw new Error('Set ANAL_PROBE_URL or Background URL');
  const r = spawnSync(
    process.execPath,
    [
      // prefer local dist when monorepo-linked; else npx
      ...(process.env.ANAL_PROBE_CLI
        ? [process.env.ANAL_PROBE_CLI, targetUrl, '--json', ...args]
        : ['--experimental-vm-modules']), // placeholder if using npx below
    ],
    { encoding: 'utf8', env: process.env },
  );
  // Prefer npx when ANAL_PROBE_CLI unset
  const out = process.env.ANAL_PROBE_CLI
    ? r.stdout
    : spawnSync('npx', ['--yes', 'github:newsengine/vibetesting-agent', targetUrl, '--json', ...args], {
        encoding: 'utf8',
        env: process.env,
        shell: process.platform === 'win32',
      }).stdout;
  const data = JSON.parse(out);
  lastFindings = data.findings || data;
  lastSummary = data.summary || null;
  return data;
}

Given('the deployed application at {string}', (url) => {
  targetUrl = url;
});

Given('vibetesting-agent is available via npx', () => {
  /* no-op — runProbe uses npx */
});

Given('finding {string} is monitored', (_id) => {
  /* tracked via scenario tags / id */
});

When('I run a full black-box scan', () => {
  runProbe([]);
});

When('I scan category {string}', (cat) => {
  runProbe(['--only', cat]);
});

When('I run a full black-box scan with baseline', () => {
  const baseline = process.env.ANAL_PROBE_BASELINE;
  runProbe(baseline ? ['--baseline', baseline] : []);
});

Then('finding {string} should pass', (id) => {
  const f = lastFindings.find((x) => x.id === id);
  assert.ok(f, \`finding \${id} not in scan results\`);
  assert.equal(f.pass, true, \`\${id} still failing: \${f.detail}\`);
});

Then('finding {string} should eventually pass', (id) => {
  // Soft gate during fix-in-progress: log but do not fail unless STRICT=1
  const f = lastFindings.find((x) => x.id === id);
  if (!f) return;
  if (process.env.STRICT === '1') {
    assert.equal(f.pass, true, \`\${id} still failing: \${f.detail}\`);
  }
});

Then('there should be no high severity failures', () => {
  const highs = lastFindings.filter((f) => !f.pass && f.severity === 'high');
  assert.equal(highs.length, 0, highs.map((h) => h.id).join(', '));
});

Then('there should be no new high severity failures', () => {
  const highs = lastFindings.filter((f) => !f.pass && f.severity === 'high');
  assert.equal(highs.length, 0, highs.map((h) => h.id).join(', '));
});

Then('the security grade should be at least {string}', (min) => {
  const order = ['F', 'D', 'C', 'B', 'A'];
  // grade computed only if you extend JSON — skip if missing
  if (!lastSummary?.grade) return;
  assert.ok(order.indexOf(lastSummary.grade) >= order.indexOf(min));
});
`;
}
